name: pokedex
description: Flutter pokedex app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    # - family: CustomIcons
    #   fonts:
    #     - asset: assets/fonts/CustomIcons.ttf
    - family: PokemonSolid
      fonts:
        - asset: assets/fonts/Pokemon_solid.ttf
    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/Pokemon_hollow.ttf